### ISSUE TITLE
mulitple folders in .adr-dir

### ISSUE THREAD

**Issue by jeevemula** [npryce/adr-tools#51]
Hi I am managing a folder structure as belows: 

`doc > architecture > front-end`
`doc > architecture > back-end`

Every time I use adr new I had to overwrite .adr-dir file.

Is there a way to accommodate multiple folder structure.

**Comment by npryce** [comment]
Not something I'd thought of before.

If you want to document decisions about different components of the architecture, instead of the overall system architecture, could you run adr-tool in the subdirectory for that tool?

E.g. if you have a repo structure like:

```
<project-root>/
   +-- back-end/
   |
   +-- front-end/
```

You could run cd into back-end and run `adr init`, then into front-end/ and run `adr-init`, to have an ADR log for each component. And you could also have an ADR log under the root for recording decisions that affect the whole system.

**Comment by npryce** [comment]
Would feature suggested by #48 be a solution?  If that was implemented, you could wrap adr-tool in project-specific scripts that would enforce a distinction between your app components.

**Comment by npryce** [comment]
Closing because you can use `adr init` to create multiple ADR directories in the same Git repo already, and because this use case would be supported by #48.
