### ISSUE TITLE
Add option for having status values use shields.io

### ISSUE THREAD

**Issue by eoghain** [npryce/adr-tools#70]
Github users have been conditioned to look for shields.io tags as a quick way to understand the state of a repo.  It'd be great if the Status section that is generated could replace the STATUS with a shields.io image instead of using just plain text.

Examples:
![Accepted](https://img.shields.io/badge/Status-Accepted-green.svg)  
![Rejected](https://img.shields.io/badge/Status-Rejected-red.svg)  
![Superceded](https://img.shields.io/badge/Status-Superceded-lightgrey.svg)  

For clarity I'm thinking of a command line switch:
`adr --shields new URL Scheme`
`adr --shields new -s 1 Updated URL Scheme`

**Comment by npryce** [comment]
That would make it difficult to write scripts that work with ADR files. Maybe this could be done in the publishing pipeline, rather than maintained in the source

**Comment by PeterMTaylor** [comment]
To suggest from a Powershell point of view examining the state of files being tested as one example here which updates status badge.
http://wragg.io/add-a-code-coverage-badge-to-your-powershell-deployment-pipeline/

**Comment by eoghain** [comment]
I don't see how it's any more difficult than plain strings. It's just a different regex. As long as the tool defines the the set of possible strings it'd be simple enough. Also I'm thinking of this as an optional choice that people can opt into using not a replacement for the plain strings.

**Comment by npryce** [comment]
I think that this is not a feature I can support in adr-tools, because:

* ADRs are intended to be stored long-term to document how an architecture evolves over time.  (Some of the systems we have are 25 years old, for example).  Therefore the machine-readable parts of the documentation format are designed to be as stable as possible.  Web services have a shorter lifetime. Links to a service will likely become out of date and so shouldn't be used for the machine-readable parts of the document.
* Other tools also parse ADRs in the format managed by adr-tools -- Documentation pipelines, architecture visualisation tools like [structrizr](https://structurizr.com/help/decision-log), etc.   They would have to be understand the configuration to correctly parse out the data.
* Displaying status information visually is a view concern, and is best managed in the document publishing pipeline where it can be varied independently of the long-term storage of stable information.  This can be done with a [Pandoc filter](https://pandoc.org/filters.html), for example.

**Comment by eoghain** [comment]
@npryce Thanks for taking a look.  Everything you've said makes sense.  Moving this into a visualizer is probably a good idea.
